# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JSONBookDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SDWebImage', '~> 5.0'

  target 'JSONBookDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JSONBookDemoUITests' do
    # Pods for testing
  end

end
